CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
REPEAT_KEY_ENABLE = no
COMBO_ENABLE = yes
# DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes
LTO_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Space saving
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
EXTRAKEY_ENABLE = no
UNICODE_ENABLE = no
SWAP_HANDS_ENABLE= no

# Debugging
# CONSOLE_ENABLE = yes
# KEYCODE_STRING_ENABLE = yes
